spring:
  datasource:
    url: 'jdbc:postgresql://postgres:5432/template'
  flyway:
    enabled: 'true'
    locations: 'classpath:db/migration,classpath:db/testdata'
    url: 'jdbc:postgresql://postgres:5432/template'